FROM python:3.12-slim

WORKDIR /app

COPY requirements.doc_worker.txt .
RUN pip install --no-cache-dir -r requirements.doc_worker.txt

COPY . .

ENV PORT=8080

EXPOSE 8080

CMD uvicorn main_doc_worker:app --host 0.0.0.0 --port $PORT --log-level debug
